### ISSUE TITLE
为什么选择beego呢  感觉现在用的人不多了吧

### ISSUE THREAD

**Issue by Yakumo-Yukari** [1920853199/go-blog#10]
感觉现在gin   iris echo 这些比较主流  或者使用 gofiber 也不错的

beego给人的感觉就是臃肿笨重

**Comment by 1920853199** [comment]
因为吧，其实这个项目是我刚开始接触go的时候的一个练手项目，后面很多人说，代码写得还可以，所以就继续拓展了一下。
