### ISSUE TITLE
关于代码质量的请教

### ISSUE THREAD

**Issue by mogody** [1920853199/go-blog#11]
看了好多 go 语言的项目，在代码质量这一块，对于变量命名为啥都是 a b c d 这样的单字母风格，好一点的话就是用缩写，虽然说都看得懂，但是这样的命名风格可读性真的不行

比如 Context 用 c 命名，Model 用 m 命名，不知道这个是刻意为之，还是说 go 语言的哲学就是这样

**Comment by wwhai** [comment]
> 看了好多 go 语言的项目，在代码质量这一块，对于变量命名为啥都是 a b c d 这样的单字母风格，好一点的话就是用缩写，虽然说都看得懂，但是这样的命名风格可读性真的不行
> 
> 比如 Context 用 c 命名，Model 用 m 命名，不知道这个是刻意为之，还是说 go 语言的哲学就是这样

 go 语言的哲学就是这样，变量取自类型第一个字母
