### ISSUE TITLE
已经通过docker拉到服务器上了，网页打开不来是怎么回事

### ISSUE THREAD

**Issue by wendao365** [1920853199/go-blog#8]

**Comment by 1920853199** [comment]
你看一下端口有没有打开了，或者查看一下docker看看报什么错，我验证过应该是没问题的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月20日(周四) 下午5:14
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [1920853199/go-blog] 已经通过docker拉到服务器上了，网页打开不来是怎么回事 (#8)

**Comment by wendao365** [comment]
端口是开了的，也没有报错，感谢指导




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "1920853199/go-blog"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月20日(星期四) 下午5:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [1920853199/go-blog] 已经通过docker拉到服务器上了，网页打开不来是怎么回事 (#8)





 你看一下端口有没有打开了，或者查看一下docker看看报什么错，我验证过应该是没问题的 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2021年5月20日(周四) 下午5:14 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.***&amp;gt;; 
 主题: [1920853199/go-blog] 已经通过docker拉到服务器上了，网页打开不来是怎么回事 (#8)

**Comment by 1920853199** [comment]
是否用的是云服务器呢，如果是云服务器的话，一般端口都不会开放的。或者你进容器看日志

**Comment by wendao365** [comment]
查看了日志，报错为
[ORM]2021/05/25 06:05:35 register db Ping `default`, Error 1049: Unknown database 'go-blog'
2021/05/25 06:05:35.454 [I] [asm_amd64.s:1373]  http server Running on http://:8080
因为建数据库时命名不让go-blog，所以建成了go_blog
这种情况需要怎么修改一下

**Comment by crazyn2** [comment]
> 查看了日志，报错为
> [ORM]2021/05/25 06:05:35 register db Ping `default`, Error 1049: Unknown database 'go-blog'
> 2021/05/25 06:05:35.454 [I] [asm_amd64.s:1373] http server Running on http://:8080
> 因为建数据库时命名不让go-blog，所以建成了go_blog
> 这种情况需要怎么修改一下

建表语句中用反引号括住go-blog

**Comment by 1920853199** [comment]
> 查看了日志，报错为
> [ORM]2021/05/25 06:05:35 register db Ping `default`, Error 1049: Unknown database 'go-blog'
> 2021/05/25 06:05:35.454 [I] [asm_amd64.s:1373] http server Running on http://:8080
> 因为建数据库时命名不让go-blog，所以建成了go_blog
> 这种情况需要怎么修改一下

也可以通过创建配置文件然后挂载到/work/conf/目录下
