### ISSUE TITLE
社区前端建议  左侧在未登录的情况下显示快捷登录

### ISSUE THREAD

**Issue by Yakumo-Yukari** [1920853199/go-blog#9]
![1](https://user-images.githubusercontent.com/12076232/124086176-60879000-da83-11eb-8ac0-d9d1c613eadb.png)
![2](https://user-images.githubusercontent.com/12076232/124086183-62515380-da83-11eb-8a19-092799613703.png)
![3](https://user-images.githubusercontent.com/12076232/124086186-62e9ea00-da83-11eb-8372-d30efed46912.png)

不然你的社区布局就会很奇怪

**Comment by 1920853199** [comment]
这个问题今天已经处理了呢

**Comment by 1920853199** [comment]
显示未登录，然后显示登录的布局是个挺不错的建议，谢谢哦
